site_name: No Precinho

repo_name: "2024.1-No-Precinho"

repo_url: https://github.com/mdsreq-fga-unb/2024.1-No-Precinho

theme:
  name: 'material'
  nav_style: dark
  language: pt-BR
  logo: 'imagens/brasao.png'
  favicon: 'imagens/favico.ico'

  icon:
    repo: fontawesome/brands/github
  

  palette:
    - scheme: slate
      primary: 'indigo' # Um azul escuro como substituto para o preto
      accent: 'light blue' # MantÃ©m o azul claro para o destaque
      toggle:
        icon: 'material/toggle-switch-off-outline'
        name: 'Deslize para o modo claro'
    
    - scheme: default
      primary: 'blue' # Um azul padrÃ£o que pode ser adequado para o azul escuro
      accent: 'light blue' # MantÃ©m o azul claro para o destaque
      toggle:
        icon: 'material/toggle-switch'
        name: 'Deslize para o modo escuro'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


nav:
  - ğŸ  Pagina inicial: index.md
  - ğŸŒ Liga do CÃ³digo: faccao.md
  - ğŸš€ VisÃ£o Geral do Produto: visao-geral-produto.md
  - ğŸ—ƒ VisÃ£o Geral do Projeto: visao-geral-projeto.md
  - âš™ï¸ Processo de Desenvolvimento de Software:  pds.md
  - ğŸ“š LiÃ§Ãµes Aprendidas: licoes-aprendidas.md
  - ğŸ“ Material do SeminÃ¡rio : seminario.md